FROM php:7.2-apache

COPY ./files/index.php /var/www/html/
COPY ./files/apache2.conf /etc/apache2/apache2.conf
COPY ./files/ports.conf /etc/apache2/ports.conf

RUN service apache2 restart

EXPOSE 8080